# Generated by Django 5.1.1 on 2024-10-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cables',
            fields=[
                ('referencia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_restante', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=1)),
                ('ultima_advertencia', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cables',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajePruebaDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topic1',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('proyecto', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tipo_proyecto', models.CharField(choices=[('OT', 'OT'), ('OI', 'OI')], max_length=2)),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'proyectos',
                'unique_together': {('tipo_proyecto', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Tableros',
            fields=[
                ('identificador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.proyectos')),
            ],
            options={
                'db_table': 'tableros',
                'unique_together': {('proyecto', 'item')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dispensada', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cables')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.proyectos')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tableros')),
            ],
            options={
                'db_table': 'registro_dispensas',
            },
        ),
    ]
