# Generated by Django 5.1 on 2024-08-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cables',
            name='stock_minimo',
            field=models.IntegerField(default=1),
        ),
    ]
