# Generated by Django 5.1.1 on 2024-10-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_registrodispensa_cantidad_restante_en_momento_de_dispensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodispensa',
            name='cantidad_restante_en_momento_de_dispensa',
        ),
    ]
