# Generated by Django 5.1 on 2024-09-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_cables_stock_minimo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seteo',
        ),
    ]
