# Generated by Django 5.1.1 on 2024-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_registrodispensa_cantidad_restante_en_momento_de_dispensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cables',
            name='cantidad_restante_original',
            field=models.IntegerField(default=0),
        ),
    ]
