# Generated by Django 5.1.1 on 2024-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cables_cantidad_restante_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cables',
            name='cantidad_restante_original',
        ),
        migrations.AddField(
            model_name='registrodispensa',
            name='cantidad_restante_despues',
            field=models.IntegerField(default=0),
        ),
    ]
