# Generated by Django 5.1.1 on 2024-10-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_cables_cantidad_restante_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodispensa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuarios'),
        ),
    ]
