# Generated by Django 5.1.1 on 2024-10-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_registrodispensa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
