# Generated by Django 5.1.1 on 2024-11-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_usuarios_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp', models.CharField(max_length=100)),
                ('encoder', models.CharField(max_length=100)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cables')),
            ],
            options={
                'unique_together': {('cable', 'esp', 'encoder')},
            },
        ),
    ]
