# Generated by Django 5.1.1 on 2024-11-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_configuracioncable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracioncable',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='configuracioncable',
            table='configuracion_cables',
        ),
    ]
