# Generated by Django 5.1.1 on 2024-11-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_configuracioncable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracioncable',
            unique_together={('esp', 'encoder')},
        ),
    ]
