# Generated by Django 5.1.1 on 2024-11-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_configuracioncable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracioncable',
            unique_together={('esp', 'encoder')},
        ),
        migrations.AlterField(
            model_name='configuracioncable',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cables'),
        ),
    ]
