# Generated by Django 5.1.1 on 2024-11-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_registrodispensa_reproceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cables',
            name='ultima_advertencia',
        ),
    ]
