# Generated by Django 5.1.1 on 2024-12-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_coladispensa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColaDispensa',
        ),
    ]
