# Generated by Django 5.1.1 on 2024-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_solicitudcola'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcola',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
