# Generated by Django 5.1.1 on 2024-12-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_solicitudcola_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('solicitud_time', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cables')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='SolicitudCola',
        ),
    ]
