# Generated by Django 5.1.1 on 2024-12-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_colasolicitud_delete_solicitudcola'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_referencia', models.CharField(max_length=255)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuarios')),
            ],
            options={
                'db_table': 'solicitudes_cola',
            },
        ),
        migrations.DeleteModel(
            name='ColaSolicitud',
        ),
    ]
